package com.hust.achievement.domain;

public class Achievement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.category
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.description
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.name
     *
     * @return the value of achievement.name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.name
     *
     * @param name the value for achievement.name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.category
     *
     * @return the value of achievement.category
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.category
     *
     * @param category the value for achievement.category
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.description
     *
     * @return the value of achievement.description
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.description
     *
     * @param description the value for achievement.description
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}