package com.hust.achievement.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.student_number
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.student_number
     *
     * @return the value of users.student_number
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.student_number
     *
     * @param studentNumber the value for users.student_number
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}