package com.hust.achievement.domain;

public class UserAchievement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_achievement.student_number
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_achievement.achievement_name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String achievementName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_achievement.status
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_achievement.student_number
     *
     * @return the value of users_achievement.student_number
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_achievement.student_number
     *
     * @param studentNumber the value for users_achievement.student_number
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_achievement.achievement_name
     *
     * @return the value of users_achievement.achievement_name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getAchievementName() {
        return achievementName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_achievement.achievement_name
     *
     * @param achievementName the value for users_achievement.achievement_name
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setAchievementName(String achievementName) {
        this.achievementName = achievementName == null ? null : achievementName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_achievement.status
     *
     * @return the value of users_achievement.status
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_achievement.status
     *
     * @param status the value for users_achievement.status
     *
     * @mbggenerated Thu Jul 21 15:27:01 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}