package com.hust.achievement.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hust.achievement.domain.Achievement;
import com.hust.achievement.domain.AchievementExample;

public interface AchievementMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table achievement
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int countByExample(AchievementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table achievement
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	List<Achievement> selectByExampleWithBLOBs(AchievementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table achievement
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	List<Achievement> selectByExample(AchievementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table achievement
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	Achievement selectByPrimaryKey(String name);

	/**
	 * This method is used for getting all the names of achievement.
	 */
	List<String> selectAllAchievementNames();

	/**
	 * This method is used for getting all the achievements done by the user.
	 * 
	 * @param studentNumber
	 *            user's student number.
	 * @return the list of achievements.
	 */
	List<Achievement> selectAllDoneAchievements(@Param("studentNumber") String studentNumber);
}