package com.hust.achievement.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hust.achievement.domain.Days;
import com.hust.achievement.domain.DaysExample;

public interface DaysMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int countByExample(DaysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int insert(Days record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int insertSelective(Days record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	List<Days> selectByExample(DaysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	Days selectByPrimaryKey(String studentNumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Days record, @Param("example") DaysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int updateByExample(@Param("record") Days record, @Param("example") DaysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int updateByPrimaryKeySelective(Days record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table days
	 *
	 * @mbggenerated Thu Jul 21 15:27:01 CST 2016
	 */
	int updateByPrimaryKey(Days record);

	/**
	 * This method is used for user signing in.
	 * 
	 * @param studentNumber
	 *            user's student number
	 * @return sum of affected rows
	 */
	int sign(String studentNumber);
}